sudo: false

language: go

go:
  - 1.13

services:
  - docker

before_install:
  - go get -u golang.org/x/lint/golint
  - go get -u github.com/jteeuwen/go-bindata/...

script:
  - go generate
  - make

after_success:
  - test -n "$TRAVIS_TAG" && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash -s -- --rm-dist
  verbose: true
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux

notifications:
  email:
    on_success: never
